services:
  db_backend:
    ports:
      - 3306:3306

  php_backend:
    build:
      context: .
      args:
        INSTALL_XDEBUG: false
    volumes:
      - ./src/backend:/var/www/backend/current/:cached

  certbot:
    build:
      context: ./build/certbot
    volumes:
      - ./certs:/etc/nginx/certs
      - ./certs:/etc/letsencrypt
      - ./certbot:/var/www/certbot

  webserver:
    volumes:
      - ./src/backend:/var/www/backend/current/:cached
      - ./certs:/etc/nginx/certs
      - ./certbot:/var/www/certbot
      - ./certs:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    environment:
      BACKEND_SERVER_NAME: "bakosdietas.hu"
    depends_on:
      - certbot