services:
  db_backend:
    ports:
      - 3306:3306

  php_backend:
    build:
      context: .
      args:
        INSTALL_XDEBUG: false
    volumes:
      - ./src/backend:/var/www/backend/current/:cached

  certbot:
    build:
      context: ./build/certbot
    container_name: ${COMPOSE_PROJECT_NAME}-certbot
    volumes:
      - ./letsencrypt:/etc/letsencrypt
      - ./certs:/etc/nginx/certs
      - ./certbot:/var/www/certbot
    environment:
      BACKEND_SERVER_NAME: "bakosdietas.hu"

  webserver:
    depends_on:
      - certbot
    volumes:
      - ./src/backend:/var/www/backend/current/:cached
      - ./letsencrypt:/etc/letsencrypt:ro
      - ./certs:/etc/nginx/certs
      - ./certbot:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    environment:
      BACKEND_SERVER_NAME: "bakosdietas.hu"