services:
  db_backend:
    ports:
      - 3306:3306

  php_backend:
    build:
      context: .
      args:
        INSTALL_XDEBUG: false
    volumes:
      - ./src/backend:/var/www/backend/current/:cached

  webserver:
    volumes:
      - ./src/backend:/var/www/backend/current/:cached
      - ./certs:/etc/letsencrypt
      - ./certbot:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    environment:
      BACKEND_SERVER_NAME: "bakosdietas.hu"