name: Deploy Docker Environment to Server

on:
  workflow_dispatch:
  push:
    branches:
      - production

jobs:
  deploy:
    name: Deploy to Production Server
    runs-on: ubuntu-latest
    environment: production 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH (in runner)
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Sync project to server (copy from runner to server)
        run: |
          rsync -az -e "ssh -i ~/.ssh/id_ed25519" ./ ${{ secrets.DEPLOY_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.DEPLOY_DIR }}

      - name: Set up environment file
        run: |
          ssh ${{ secrets.DEPLOY_USER }}@${{ secrets.SSH_HOST }} "\
            cp '${{ secrets.DEPLOY_DIR }}/.env.example' '${{ secrets.DEPLOY_DIR }}/.env' && \
            cp '${{ secrets.DEPLOY_DIR }}/docker-compose.override.yml' '${{ secrets.DEPLOY_DIR }}/docker-compose.override.yml'"

      - name: Build and run Docker containers
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no ${{ secrets.DEPLOY_USER }}@${{ secrets.SSH_HOST }} "\
            cd '${{ secrets.DEPLOY_DIR }}' && \
            docker compose pull && \
            docker compose build && \
            docker compose up -d --remove-orphans"